version: '3.7'
services:
  postgresql:
    image: postgres:17.0
    env_file: .env
    ports:
      - 6432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  redis:
    image: redis:7.0.14
    env_file: .env
    command: redis-server --appendonly yes  # enable persistent storage
    volumes:
      - redisdata:/data
    networks:
      - my-network

  app:
    build:
      context: .
      dockerfile: .ci/docker/Dockerfile.rails
    depends_on:
      - postgresql
      - redis
    expose:
      - 3000:3000
    env_file: .env
    entrypoint: .ci/entrypoints/app-entrypoint.sh
    volumes:
      - .:/rails
    networks:
      - my-network

  web:
    build:
      context: .
      dockerfile: ./.ci/docker/Dockerfile.web
    depends_on:
      - app
      - sidekiq
      - postgresql
      - redis
    ports:
      - 80:80
    volumes:
      - .:/rails
    networks:
      - my-network

  sidekiq:
    build:
      context: .
      dockerfile: .ci/docker/Dockerfile.sidekiq
    depends_on:
      - app
      - postgresql
      - redis
    env_file: .env
    entrypoint: .ci/entrypoints/sidekiq-entrypoint.sh
    volumes:
      - .:/rails
    networks:
      - my-network

  easynmt:
    image: easynmt/api:2.0-cpu
    env_file: .env
    expose:
      - 24080:80
    networks:
      - my-network

volumes:
  redisdata:
  postgres_data:

networks:
  my-network:
    external: true
