FROM nginx

#Install dependencies
RUN apt-get update -qq && apt-get -y install apache2-utils

#Set an environment variable for the Rails app root folder
ENV RAILS_ROOT /rails

#Create the working directory
RUN mkdir -p $RAILS_ROOT

WORKDIR $RAILS_ROOT

RUN mkdir log

COPY public public/

COPY .ci/docker/web/nginx/nginx.conf /tmp/app.conf
COPY .ci/entrypoints/nginx-entrypoint.sh /rails/.ci/entrypoints/nginx-entrypoint.sh
RUN chmod +x /rails/.ci/entrypoints/nginx-entrypoint.sh

EXPOSE 80
ENTRYPOINT ["/rails/.ci/entrypoints/nginx-entrypoint.sh"]
